<?php

/**
 * This file is part of Bic Engine package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Ui\Win32\Internal\User32;

/**
 * @internal This is an internal library class, please do not use it in your code.
 * @psalm-internal Bic\Ui\Win32
 */
final class VirtualKey
{
    public const VK_LBUTTON                              = 0x01;
    public const VK_RBUTTON                              = 0x02;
    public const VK_CANCEL                               = 0x03;
    public const VK_MBUTTON                              = 0x04;    /* NOT contiguous with L & RBUTTON */
    public const VK_XBUTTON1                             = 0x05;    /* NOT contiguous with L & RBUTTON */
    public const VK_XBUTTON2                             = 0x06;    /* NOT contiguous with L & RBUTTON */
    public const VK_BACK                                 = 0x08;
    public const VK_TAB                                  = 0x09;
    public const VK_CLEAR                                = 0x0C;
    public const VK_RETURN                               = 0x0D;
    public const VK_SHIFT                                = 0x10;
    public const VK_CONTROL                              = 0x11;
    public const VK_MENU                                 = 0x12;
    public const VK_PAUSE                                = 0x13;
    public const VK_CAPITAL                              = 0x14;
    public const VK_KANA                                 = 0x15;
    public const VK_HANGEUL                              = 0x15;  /* old name - should be here for compatibility */
    public const VK_HANGUL                               = 0x15;
    public const VK_IME_ON                               = 0x16;
    public const VK_JUNJA                                = 0x17;
    public const VK_FINAL                                = 0x18;
    public const VK_HANJA                                = 0x19;
    public const VK_KANJI                                = 0x19;
    public const VK_IME_OFF                              = 0x1A;
    public const VK_ESCAPE                               = 0x1B;
    public const VK_CONVERT                              = 0x1C;
    public const VK_NONCONVERT                           = 0x1D;
    public const VK_ACCEPT                               = 0x1E;
    public const VK_MODECHANGE                           = 0x1F;
    public const VK_SPACE                                = 0x20;
    public const VK_PRIOR                                = 0x21;
    public const VK_NEXT                                 = 0x22;
    public const VK_END                                  = 0x23;
    public const VK_HOME                                 = 0x24;
    public const VK_LEFT                                 = 0x25;
    public const VK_UP                                   = 0x26;
    public const VK_RIGHT                                = 0x27;
    public const VK_DOWN                                 = 0x28;
    public const VK_SELECT                               = 0x29;
    public const VK_PRINT                                = 0x2A;
    public const VK_EXECUTE                              = 0x2B;
    public const VK_SNAPSHOT                             = 0x2C;
    public const VK_INSERT                               = 0x2D;
    public const VK_DELETE                               = 0x2E;
    public const VK_HELP                                 = 0x2F;
    public const VK_LWIN                                 = 0x5B;
    public const VK_RWIN                                 = 0x5C;
    public const VK_APPS                                 = 0x5D;
    public const VK_SLEEP                                = 0x5F;
    public const VK_NUMPAD0                              = 0x60;
    public const VK_NUMPAD1                              = 0x61;
    public const VK_NUMPAD2                              = 0x62;
    public const VK_NUMPAD3                              = 0x63;
    public const VK_NUMPAD4                              = 0x64;
    public const VK_NUMPAD5                              = 0x65;
    public const VK_NUMPAD6                              = 0x66;
    public const VK_NUMPAD7                              = 0x67;
    public const VK_NUMPAD8                              = 0x68;
    public const VK_NUMPAD9                              = 0x69;
    public const VK_MULTIPLY                             = 0x6A;
    public const VK_ADD                                  = 0x6B;
    public const VK_SEPARATOR                            = 0x6C;
    public const VK_SUBTRACT                             = 0x6D;
    public const VK_DECIMAL                              = 0x6E;
    public const VK_DIVIDE                               = 0x6F;
    public const VK_F1                                   = 0x70;
    public const VK_F2                                   = 0x71;
    public const VK_F3                                   = 0x72;
    public const VK_F4                                   = 0x73;
    public const VK_F5                                   = 0x74;
    public const VK_F6                                   = 0x75;
    public const VK_F7                                   = 0x76;
    public const VK_F8                                   = 0x77;
    public const VK_F9                                   = 0x78;
    public const VK_F10                                  = 0x79;
    public const VK_F11                                  = 0x7A;
    public const VK_F12                                  = 0x7B;
    public const VK_F13                                  = 0x7C;
    public const VK_F14                                  = 0x7D;
    public const VK_F15                                  = 0x7E;
    public const VK_F16                                  = 0x7F;
    public const VK_F17                                  = 0x80;
    public const VK_F18                                  = 0x81;
    public const VK_F19                                  = 0x82;
    public const VK_F20                                  = 0x83;
    public const VK_F21                                  = 0x84;
    public const VK_F22                                  = 0x85;
    public const VK_F23                                  = 0x86;
    public const VK_F24                                  = 0x87;
    public const VK_NAVIGATION_VIEW                      = 0x88; // reserved
    public const VK_NAVIGATION_MENU                      = 0x89; // reserved
    public const VK_NAVIGATION_UP                        = 0x8A; // reserved
    public const VK_NAVIGATION_DOWN                      = 0x8B; // reserved
    public const VK_NAVIGATION_LEFT                      = 0x8C; // reserved
    public const VK_NAVIGATION_RIGHT                     = 0x8D; // reserved
    public const VK_NAVIGATION_ACCEPT                    = 0x8E; // reserved
    public const VK_NAVIGATION_CANCEL                    = 0x8F; // reserved
    public const VK_NUMLOCK                              = 0x90;
    public const VK_SCROLL                               = 0x91;
    public const VK_OEM_NEC_EQUAL                        = 0x92;   // '=' key on numpad
    public const VK_OEM_FJ_JISHO                         = 0x92;   // 'Dictionary' key
    public const VK_OEM_FJ_MASSHOU                       = 0x93;   // 'Unregister word' key
    public const VK_OEM_FJ_TOUROKU                       = 0x94;   // 'Register word' key
    public const VK_OEM_FJ_LOYA                          = 0x95;   // 'Left OYAYUBI' key
    public const VK_OEM_FJ_ROYA                          = 0x96;   // 'Right OYAYUBI' key
    public const VK_LSHIFT                               = 0xA0;
    public const VK_RSHIFT                               = 0xA1;
    public const VK_LCONTROL                             = 0xA2;
    public const VK_RCONTROL                             = 0xA3;
    public const VK_LMENU                                = 0xA4;
    public const VK_RMENU                                = 0xA5;
    public const VK_BROWSER_BACK                         = 0xA6;
    public const VK_BROWSER_FORWARD                      = 0xA7;
    public const VK_BROWSER_REFRESH                      = 0xA8;
    public const VK_BROWSER_STOP                         = 0xA9;
    public const VK_BROWSER_SEARCH                       = 0xAA;
    public const VK_BROWSER_FAVORITES                    = 0xAB;
    public const VK_BROWSER_HOME                         = 0xAC;
    public const VK_VOLUME_MUTE                          = 0xAD;
    public const VK_VOLUME_DOWN                          = 0xAE;
    public const VK_VOLUME_UP                            = 0xAF;
    public const VK_MEDIA_NEXT_TRACK                     = 0xB0;
    public const VK_MEDIA_PREV_TRACK                     = 0xB1;
    public const VK_MEDIA_STOP                           = 0xB2;
    public const VK_MEDIA_PLAY_PAUSE                     = 0xB3;
    public const VK_LAUNCH_MAIL                          = 0xB4;
    public const VK_LAUNCH_MEDIA_SELECT                  = 0xB5;
    public const VK_LAUNCH_APP1                          = 0xB6;
    public const VK_LAUNCH_APP2                          = 0xB7;
    public const VK_OEM_1                                = 0xBA;   // ';:' for US
    public const VK_OEM_PLUS                             = 0xBB;   // '+' any country
    public const VK_OEM_COMMA                            = 0xBC;   // ',' any country
    public const VK_OEM_MINUS                            = 0xBD;   // '-' any country
    public const VK_OEM_PERIOD                           = 0xBE;   // '.' any country
    public const VK_OEM_2                                = 0xBF;   // '/?' for US
    public const VK_OEM_3                                = 0xC0;   // '`~' for US
    public const VK_GAMEPAD_A                            = 0xC3; // reserved
    public const VK_GAMEPAD_B                            = 0xC4; // reserved
    public const VK_GAMEPAD_X                            = 0xC5; // reserved
    public const VK_GAMEPAD_Y                            = 0xC6; // reserved
    public const VK_GAMEPAD_RIGHT_SHOULDER               = 0xC7; // reserved
    public const VK_GAMEPAD_LEFT_SHOULDER                = 0xC8; // reserved
    public const VK_GAMEPAD_LEFT_TRIGGER                 = 0xC9; // reserved
    public const VK_GAMEPAD_RIGHT_TRIGGER                = 0xCA; // reserved
    public const VK_GAMEPAD_DPAD_UP                      = 0xCB; // reserved
    public const VK_GAMEPAD_DPAD_DOWN                    = 0xCC; // reserved
    public const VK_GAMEPAD_DPAD_LEFT                    = 0xCD; // reserved
    public const VK_GAMEPAD_DPAD_RIGHT                   = 0xCE; // reserved
    public const VK_GAMEPAD_MENU                         = 0xCF; // reserved
    public const VK_GAMEPAD_VIEW                         = 0xD0; // reserved
    public const VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON       = 0xD1; // reserved
    public const VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON      = 0xD2; // reserved
    public const VK_GAMEPAD_LEFT_THUMBSTICK_UP           = 0xD3; // reserved
    public const VK_GAMEPAD_LEFT_THUMBSTICK_DOWN         = 0xD4; // reserved
    public const VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT        = 0xD5; // reserved
    public const VK_GAMEPAD_LEFT_THUMBSTICK_LEFT         = 0xD6; // reserved
    public const VK_GAMEPAD_RIGHT_THUMBSTICK_UP          = 0xD7; // reserved
    public const VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN        = 0xD8; // reserved
    public const VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT       = 0xD9; // reserved
    public const VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT        = 0xDA; // reserved
    public const VK_OEM_4                                = 0xDB;  //  '[{' for US
    public const VK_OEM_5                                = 0xDC;  //  '\|' for US
    public const VK_OEM_6                                = 0xDD;  //  ']}' for US
    public const VK_OEM_7                                = 0xDE;  //  ''"' for US
    public const VK_OEM_8                                = 0xDF;
    public const VK_OEM_AX                               = 0xE1;  //  'AX' key on Japanese AX kbd
    public const VK_OEM_102                              = 0xE2;  //  "<>" or "\|" on RT 102-key kbd.
    public const VK_ICO_HELP                             = 0xE3;  //  Help key on ICO
    public const VK_ICO_00                               = 0xE4;  //  00 key on ICO
    public const VK_PROCESSKEY                           = 0xE5;
    public const VK_ICO_CLEAR                            = 0xE6;
    public const VK_PACKET                               = 0xE7;
    public const VK_OEM_RESET                            = 0xE9;
    public const VK_OEM_JUMP                             = 0xEA;
    public const VK_OEM_PA1                              = 0xEB;
    public const VK_OEM_PA2                              = 0xEC;
    public const VK_OEM_PA3                              = 0xED;
    public const VK_OEM_WSCTRL                           = 0xEE;
    public const VK_OEM_CUSEL                            = 0xEF;
    public const VK_OEM_ATTN                             = 0xF0;
    public const VK_OEM_FINISH                           = 0xF1;
    public const VK_OEM_COPY                             = 0xF2;
    public const VK_OEM_AUTO                             = 0xF3;
    public const VK_OEM_ENLW                             = 0xF4;
    public const VK_OEM_BACKTAB                          = 0xF5;
    public const VK_ATTN                                 = 0xF6;
    public const VK_CRSEL                                = 0xF7;
    public const VK_EXSEL                                = 0xF8;
    public const VK_EREOF                                = 0xF9;
    public const VK_PLAY                                 = 0xFA;
    public const VK_ZOOM                                 = 0xFB;
    public const VK_NONAME                               = 0xFC;
    public const VK_PA1                                  = 0xFD;
    public const VK_OEM_CLEAR                            = 0xFE;
}
